CREATE DATABASE DADOS_ALUNOS;

CREATE TABLE [ALUNOS](
[ID] [INT] NOT NULL PRIMARY KEY,
[NOME] [VARCHAR] (100),
[NOTA SEMESTRE 1] [DECIMAL](4, 2),
[NOTA SEMESTRE 2] [DECIMAL](4, 2),
[ANO] [VARCHAR](4),
)